# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "ata_piix" "sr_mod" "uhci_hcd" "virtio_blk" "virtio_pci" ];
    };
    loader.grub = {
      enable = true;
      version = 2;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/desktop";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = { 
    device = "/dev/disk/by-label/desktop";
    fsType = "vfat";
  };

  swapDevices = [{
    device = "/swap/swapfile";
    size = 8196;
  }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = true;

  nixpkgs.hostPlatform = "x86_64-linux";
}
